version: "3.8"

networks:
  default:
    external:
      name: backend
services:
  sahibinden-mongo:
    image: mongo:4.2
    container_name: sahibinden-mongo
    ports:
      - 27017:27017
  sahibinden:
    image: sahibinden-comment
    container_name: sahibinden
    ports:
      - 8080:8080
    links:
      - sahibinden-mongo